### ISSUE TITLE
Improve reading list

### ISSUE THREAD

**Issue by NatalieZelenka** [very-good-science/data-ethics-club#30]
How should we categorise the reading list?
* Broad topics (e.g. "machine learning", "statistics", "EDI", "law")
* Narrower topics (e.g. "explainable AI", "algorithms", "accessibility", "privacy")
* Past/Planned/Not yet read?

How should we organise the reading list:
* Separate READINGLIST.md, signposted to in README?

**Comment by ninadicara** [comment]
Meeting 13.01.2021 -
Agreed narrower topics are preferred. 
Decided Nina will try to see if AirTable sheets can be embedded in markdown. If so this would allow us to categorise each paper into multiple categories which is more likely to fit the multidisciplinary theme. 
- [ ] Nina to try embedding list into markdown
- [ ] If successful, Nina to add reading list to a table and embed. Otherwise, create a MD document with themes.

**Comment by ninadicara** [comment]
NB The AirTable thing wasn't successful! 
If we made a website it would work because we could embed it, but I also like the list being included in the version control so happy to stick with current way of doing it for now :)

**Comment by NatalieZelenka** [comment]
WE DID MAKE A WEBSITE! So, time to revisit this!

**Comment by ninadicara** [comment]
We did this!! Lets pat ourselves on the back :D
